### ISSUE TITLE
api tweaks, take 1

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#1]
_1 snake case everything everywhere
_2 use entity_id and dataset_id and topic_id and variable_id everywhere instead of id, fxf, etc. in params and response
_3 change questions to have variable + constraints and no ODN URL
_4 delete "type": "division"

in response for "Find the relatives of an entity"

**Comment by aaasen** [comment]
Deployed the fixes to staging. I'll wait until Monday to push to production since it will break Tosh's frontend changes.

**Comment by zang0** [comment]
Where's backend staging @ so I can take a look?

**Comment by aaasen** [comment]
http://odn-backend-staging.herokuapp.com/
