### ISSUE TITLE
App tokens

### ISSUE THREAD

**Issue by aaasen** [socrata/odn-backend#10]
App tokens are documented in Apiary but not yet implemented.

**Comment by zang0** [comment]
_1 pass tokens through to soql calls

**Comment by aaasen** [comment]
App tokens are required for all endpoints except for `/`. They can be passed as the `X-App-Token` header or the `app_token` parameter. All tokens are passed to Socrata using the header. Will sync with Tosh for deploy since this is a breaking change.
