### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by aaasen** [socrata/odn-backend#12]
Write a script to put a lot of load on the server to make sure that it can handle around 50 active users at a time. Run this locally and on staging. Could also run on prod. Prioritize likely URLs to warm up the cache.

**Comment by zang0** [comment]
Add to release checklist

**Comment by aaasen** [comment]
Added this. Docs here: https://github.com/socrata/odn-backend#load-tests

Main insight from load testing was that the `map/values` endpoint was too slow. It figures out the IDs that it needs to send, then makes a bunch of requests to get the GeoJSON and values for those IDs. Since it has to wait for every one of those requests to complete before sending data back to the user, it was taking upwards of 10s to respond when the Socrata backend was bogged down. Fixed this by implementing websockets, so it can send the data back in small chunks as it becomes available. Helped performance a lot. 

Other than that, I'm really not concerned with the performance of the service. Running a test right now with 100 concurrent users for 1 hour. Should give us an idea of how it will perform under loads around 5k request/min.

**Comment by aaasen** [comment]
Also, we have now published a script to DDoS ourselves.
