### ISSUE TITLE
ODN API should set user agent

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#25]
from @rlvoyer Requests from the ODN make up a large percentage of catalog API requests and the majority of these requests show up in our logs as having no user-agent specified. It would make it much easier to track anomalous API traffic if we knew definitively which traffic was coming from the ODN.

**Comment by aaasen** [comment]
What should the user agent be set to? Can we send app tokens to the catalog API?

**Comment by rlvoyer** [comment]
Cetera doesn't know anything about catalog API. The user-agent could be anything that is identifiable and likely to be unique. Let's impose the following constraints: 1) it should have the string "ODN" and 2) it should have an ODN version. Sound reasonable?

**Comment by aaasen** [comment]
Set it to `ODN/1.0` since that seems to be a common format.
