### ISSUE TITLE
ensure variable display names align w/ live site

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#26]
bg:

also noticing a lot of variable name differences, minor stuff, things like "Annual Change in PCE" vs same but PCE expanded

_1 related is the generated sentence "The X of Washington in 2013 blah" would need to use the display name

Lane Aasen (lane.aasan@socrata.com, lane.aasen@socrata.com)
We do have display name on the API i just haven't added it for every variable because it takes a long time

**Comment by zang0** [comment]
need to tweak: https://github.com/socrata/odn-backend/blob/master/data/sources.json to get display names aligned w/ prod and eliminate unnecessary variables.

**Comment by zang0** [comment]
Specifics:

_1 rename sub category Education in http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/education/education.education.female_percent_less_than_9th_grade/2013? to Graduation Rates - note: not seeing any way to change in odn-backend/data/sources.json

_2 add Education Places - not obvious how to add the above as well

**Comment by aaasen** [comment]
1. Fixed this. Any node in the tree can specify a `name` attribute. If it is not specified, one will be generated from the node's `id` attribute.
2. This one is harder. The education places data doesn't fit into the model of the ODN backend very well. We should discuss whether or not this is a common case that needs to be supported by the backend or if it can be a special frontend feature. 

Can we split this ticket into others and close?

**Comment by zang0** [comment]
yeah go ahead and split it. re: 2 - its a low priority not common case right now, i'm ok special frontending it for now.

**Comment by aaasen** [comment]
Additions:
 - Added high school dropout, associate's degree, and professional degree to graduation rates
 - Added median earnings by education

Cost of living, occupations, and health indicators will be slightly different because we will have more dropdown menus. We can verify the names once this feature is implemented.

Closing this ticket now. We can file more specific tickets if more discrepancies pop up.
