### ISSUE TITLE
timeseries should start in 1998 for Change in Personal Consumption Expenditures over Time

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#30]
notice 0 point in 1997 for Change in Personal Consumption Expenditures over Time plot in staging vs prod
![screen shot 2016-08-23 at 6 56 03 pm](https://cloud.githubusercontent.com/assets/1051776/17915918/50ae9700-6963-11e6-9c07-3dbd6fc51b4d.png)
![screen shot 2016-08-23 at 6 55 57 pm](https://cloud.githubusercontent.com/assets/1051776/17915919/50b2e0da-6963-11e6-81a8-ce9d4e6c2133.png)

**Comment by aaasen** [comment]
Fixed this and a similar issue with population percent change for 2009.
