### ISSUE TITLE
Ensure proper id names moving forward

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#35]
Walk through all region types, for every type, inspect data/availability results. 

_1 Make sure all variables and JSON nodes reflect desired names moving forward. So, for example in the screenshot below, the education node would be renamed graduation_rates resulting in the id being education.graduation_rates instead of education.education

_2 Create a static mapping file for each of these changes which enable the front end to recreate the old URLs

![screen shot 2016-08-31 at 10 38 56 am](https://cloud.githubusercontent.com/assets/1051776/18139633/27aade36-6f67-11e6-841d-8c1a3dc4ee09.png)

**Comment by aaasen** [comment]
Changed `education.education` to `education.graduation_rates` and `health.health` to `health.health_behaviors`. Let me know if there are any other tweaks. Will update variables dataset after all tweaks have been made.

**Comment by zang0** [comment]
_1 change:

michigan.debt
michigan.expenditures
michigan.general_fund
michigan.pensions
michigan.property_tax
michigan.revenues

to

finance.michigan_debt
finance.michigan_expenditures
finance.michigan_general_fund
finance.michigan_pensions
finance.michigan_property_tax
finance.michigan_revenues

**Comment by aaasen** [comment]
Updated variables dataset and deployed to production.
