### ISSUE TITLE
search result recall dropped vs prod

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#45]
_1 https://opendatanetwork-staging.herokuapp.com/entity/1600000US5363000/Seattle_WA/jobs.earnings.median_earnings?

note: 1 doc result

vs

http://www.opendatanetwork.com/region/1600000US5363000/Seattle_WA/earnings/median_earnings/2013?

note: 6 results

note: can't see query due to new api. #44 would help.

**Comment by aaasen** [comment]
Query on prod: 
```
(revenue OR budget OR dividend OR wage OR income OR compensation OR assets OR salary OR earnings) AND ((Seattle AND ("WA" OR "Washington")))
```

Query on staging: 
```
((Seattle AND (Washington OR WA)) AND (revenue OR budget OR dividend OR wage OR income OR compensation OR assets OR salary OR earnings))
```

The only differences are ordering and that we only quote when necessary on staging. 

[Results of production](https://api.us.socrata.com/api/catalog/v1?limit=10&offset=0&only=datasets&q_internal=(revenue%20OR%20budget%20OR%20dividend%20OR%20wage%20OR%20income%20OR%20compensation%20OR%20assets%20OR%20salary%20OR%20earnings)%20AND%20((Seattle%20AND%20(%22WA%22%20OR%20%22Washington%22))))
[Results of staging](https://api.us.socrata.com/api/catalog/v1?limit=10&offset=0&only=datasets&q_internal=((Seattle%20AND%20(Washington%20OR%20WA))%20AND%20(revenue%20OR%20budget%20OR%20dividend%20OR%20wage%20OR%20income%20OR%20compensation%20OR%20assets%20OR%20salary%20OR%20earnings)))

Results are the same, so this must just be a caching issue with production.
