### ISSUE TITLE
show cross topic questions w/ selected topic questions ranked highest

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#53]
Hey. For questions on entity pages, do we just want questions about other variables in the current dataset?
Right now, production has questions from all datasets about the first selected entity
i like the prod functionality, but in my ideal world, the results would be ranked such that the current topic questioned would be ranked higher
Lane Aasen (lane.aasan@socrata.com, lane.aasen@socrata.com)
OK. Now that we have the backend we can implement those questions without the autosuggest dataset
So we can do that
so if you're on edu, then the edu questions are at the top of the list
yeah, but i really want to focus on dialing things down and getting the release out and then a stone polishing release shortly there after

**Comment by aaasen** [comment]
This is actually covered by the frontend.
