### ISSUE TITLE
exclude null in returned data values table

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#59]
https://www.opendatanetwork.com/entity/0500000US26077/Kalamazoo_County_MI/finance.michigan_general_fund.general_fund_balance?year=2014

![screen shot 2016-09-12 at 10 16 28 am](https://cloud.githubusercontent.com/assets/1051776/18445334/eea39f50-78d1-11e6-8d5f-9b3d0bbbf47e.png)

**Comment by aaasen** [comment]
Looks like the general fund health in 2015 is 0, not null. https://mi-treasury.data.socrata.com/resource/qvun-6ew5.json?id=0500000US26077&variable=general_fund_health&year=2015&$select=variable,value,id

It's trivial to filter out null values if we want to, but it won't fix this problem.

**Comment by zang0** [comment]
lets filter out the nulls an then hand it over to kyle for setting nulls in the dataset.

**Comment by aaasen** [comment]
Added `$where=value IS NOT NULL` to chart and map value calls. I think that we are better off removing the zero rows from the dataset instead of setting them to null since a null row is useless.
